In [2]:
# installation of pandas, numpy and matplotlib
%pip install pandas
%pip install numpy

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.4.4)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np

In [4]:
file_path = "/workspaces/MiniProject1_GUVI/Uber_Eats_data.csv"
df = pd.read_csv(file_path)

In [5]:
df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [6]:
df.describe()

              votes
count  23193.000000
mean     601.074462
std     1114.854301
min        0.000000
25%      101.000000
50%      221.000000
75%      586.000000
max    16832.000000

In [7]:
df.name.values

<StringArray>
[                                                 'Jalsa',
                                         'Spice Elephant',
                                        'San Churro Cafe',
                                  'Addhuri Udupi Bhojana',
                                          'Grand Village',
                                        'Timepass Dinner',
                                                 'Onesta',
                                         'Penthouse Cafe',
                                              'Smacznego',
     'CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The Alley',
 ...
                                                'BAR BAR',
                                          'The Beer Cafe',
                                      'Pablo's Gastrobar',
                                   'Oliver's Pub & Diner',
                                                'Smaaash',
                                     'Izakaya Gastro Pub',
            'M Bar - Bengaluru Marriott Hotel Whitefield',
                                 'Keys Cafe - Keys Hotel',
                                                'Bhagini',
 'Chime - Sheraton Grand Bengaluru Whitefield Hotel &...']
Length: 23193, dtype: str

In [8]:
df.name.isnull().sum()

np.int64(0)

In [9]:
df.online_order.unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [10]:
df.online_order.isnull().sum()

np.int64(0)

In [12]:
df['book_table'].value_counts()

book_table
No     17071
Yes     6122
Name: count, dtype: int64

In [ ]:
df.rate.unique()

<StringArray>
[ '4.1/5',  '3.8/5',  '3.7/5',  '4.6/5',  '4.0/5',  '4.2/5',  '3.9/5',
  '3.0/5',  '3.6/5',  '2.8/5',  '4.4/5',  '3.1/5',  '4.3/5',  '2.6/5',
  '3.3/5',  '3.5/5', '3.8 /5',  '3.2/5',  '4.5/5',  '2.5/5',  '2.9/5',
  '3.4/5',  '2.7/5',  '4.7/5',    'NEW',  '2.4/5',  '2.2/5',  '2.3/5',
  '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5', '2.9 /5', '2.7 /5',
 '2.5 /5', '2.6 /5', '4.5 /5', '4.3 /5', '3.7 /5', '4.4 /5',  '4.9/5',
  '2.1/5',  '2.0/5',  '1.8/5', '3.4 /5', '3.6 /5', '3.3 /5', '4.6 /5',
 '4.9 /5', '3.2 /5', '3.0 /5', '2.8 /5', '3.5 /5', '3.1 /5', '4.8 /5',
 '2.3 /5', '4.7 /5', '2.4 /5', '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5']
Length: 63, dtype: str